### ISSUE TITLE
Nao está salvando os atletas dentro de jogo

### ISSUE THREAD

**Issue by luizcunha3** [fguimaraess/Sis-Atleta-v2#3]

**Comment by fguimaraess** [comment]
Tópicos alterados hoje (10/04):
Tela de Atletas:
- O clube não é mais um campo texto, e sim um combo com os clubes cadastrados no banco.
Tela de jogos:
- Tirei a requisição ao banco para trazer os clubes e atletas, visto que já é feito isso no load de suas respectivas páginas.

Pontos a resolver:
Ao criar um novo jogo, quando abro o modal de Estatísticas do Atleta, recebo o erro: 
"Uncaught TypeError: Cannot read property 'atletasTempJogo' of undefined at estatisticasAtleta (jogo.js:206)"
Os dados são salvos normalmente e o jogo é criado no banco, porém sem os Atletas.

**Comment by fguimaraess** [comment]
Salvei atletas dentro do jogo mas nao consegui editar no último commit (Cadastrado jogo com atletas).

**Comment by luizcunha3** [comment]
Fecha a porra da issue.

**Comment by luizcunha3** [comment]
Poe o id do commit quando fechar

**Comment by fguimaraess** [comment]
Resolvido. Commit e2c8826e8380cb54f39f5c18ddfe1a68aafaab9b.
